import task
from task_manager import TaskManager


def main():
    taskk1 = task.Task(1,'a','aa')
    taskk2 = task.Task(2, 'a', 'aa')
    taskk3 = task.Task(3, 'a', 'aa')
    manager = TaskManager()
    manager.create_task(taskk1)
    manager.create_task(taskk2)
    manager.create_task(taskk3)
    manager.print_tasks()
    subtaskk = task.Subtask(2,'b','bb',1)
    manager.create_subtask(subtaskk)
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()
    print(manager.get_tasks())
    print(manager.get_subtasks())
    print(manager.get_complex_tasks())
    print(manager.get_tasks_by_id(3))
    print('___________________________')
    print('remove check')
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()
    manager.remove_task_by_id(2)
    manager.remove_task_by_id(3)

    manager.create_subtask(task.Subtask(22,'b','bb',1))
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()

    manager.remove_subtask_by_id(2)
    manager.print_subtasks()
    manager.print_complex_tasks()
    manager.remove_subtask_by_id(22)
    manager.print_subtasks()
    manager.print_complex_tasks()

    print("==========check rmv complex by id")
    manager.create_task(task.Task(1, 'a', 'aa'))
    manager.create_subtask(task.Subtask(2, 'b', 'bb', 1))
    manager.create_subtask(task.Subtask(22, 'b', 'bb', 1))
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()
    manager.remove_complex_task_by_id(1)
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()

    print("==========check rmv task ")
    manager.create_task(task.Task(1, 'a', 'aa'))
    manager.create_task(task.Task(2, 'a', 'aa'))
    manager.remove_tasks()
    manager.print_tasks()

    print("==========check rmv subtasks")
    manager.create_task(task.Task(1, 'a', 'aa'))
    manager.create_task(task.Task(2, 'a', 'aa'))
    manager.create_subtask(task.Subtask(2, 'b', 'bb', 1))
    manager.create_subtask(task.Subtask(22, 'b', 'bb', 1))
    manager.remove_subtasks()
    manager.print_tasks()
    manager.print_subtasks()

    print("==========check rmv comp_tasks")
    manager.remove_tasks()
    manager.create_task(task.Task(1, 'a', 'aa'))
    manager.create_task(task.Task(2, 'a', 'aa'))
    manager.create_subtask(task.Subtask(2, 'b', 'bb', 1))
    manager.create_subtask(task.Subtask(22, 'b', 'bb', 1))
    manager.create_subtask(task.Subtask(33, 'b', 'bb', 2))
    manager.remove_complex_tasks()
    manager.print_tasks()
    manager.print_subtasks()
    manager.print_complex_tasks()



if __name__ == "__main__":
    main()
